=== mihail-jekov/fmiXMLCourse/AircraftCarrier.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT aircraft-carrier (name, personel, aircrafts, missions)>
  <!ELEMENT name (#PCDATA)>
  <!ATTLIST aircraft-carrier engine (nuclear|diesel) "nuclear">
  <!ATTLIST aircraft-carrier class CDATA #REQUIRED>
  <!ATTLIST aircraft-carrier years-of-service CDATA #IMPLIED>
  <!ELEMENT personel (soldier+)>
    <!ELEMENT soldier (first-name, last-name, gender, position, age, religion)>
      <!ATTLIST soldier id ID #REQUIRED
						aircraft IDREFS #IMPLIED
						mission IDREFS #IMPLIED>
	  <!ELEMENT first-name (#PCDATA)>
	  <!ELEMENT last-name (#PCDATA)>
      <!ELEMENT gender (#PCDATA)>
	  <!ELEMENT position (#PCDATA)>
	  <!ELEMENT age (#PCDATA)>
	  <!ELEMENT religion (#PCDATA)>
  <!ELEMENT aircrafts (aircraft+)>
    <!ELEMENT aircraft (model, manufacturer, cost, range)>
	  <!ATTLIST aircraft id ID #REQUIRED>
	  <!ATTLIST aircraft control (pilot|auto-pilot) #REQUIRED>
	  <!ATTLIST aircraft role (fighter|bomber|multirole|reconnaissance) #REQUIRED>
      <!ELEMENT model (#PCDATA)>
	  <!ELEMENT manufacturer (manufacturer-name, established, staff-count, profit)>
	    <!ELEMENT manufacturer-name (#PCDATA)>
	    <!ELEMENT established (#PCDATA)>
	    <!ELEMENT staff-count (#PCDATA)>
        <!ELEMENT profit (#PCDATA)>
      <!ELEMENT range (#PCDATA)>
	  <!ELEMENT cost (#PCDATA)>
  <!ELEMENT missions (mission*)>
    <!ELEMENT mission (code-name, countries, duration, description, units-lost)>
	  <!ATTLIST mission id ID #REQUIRED>
      <!ELEMENT code-name (#PCDATA)>
      <!ELEMENT countries (country+)>
        <!ELEMENT country (country-name, population)>
		  <!ATTLIST country continent (europe|asia|north-america|south-america|africa|antarctica) #IMPLIED>
          <!ELEMENT country-name (#PCDATA)>
		  <!ELEMENT population (#PCDATA)>
      <!ELEMENT duration (#PCDATA)>
	  <!ELEMENT description (#PCDATA)>
	  <!ELEMENT units-lost (#PCDATA)>

=== mihail-jekov/fmiXMLCourse/Valid_XML_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aircraft-carrier SYSTEM "AircraftCarrier.dtd">
<?xml-stylesheet type="text/xsl" href="HTML_Transformation_2.xsl"?>

<aircraft-carrier engine = "diesel" class = "Yorktown-class" years-of-service = "1938-1947">
	<name>USS „Ентърпрайз“ (CV-6)</name>
	<personel>
		<soldier id = "s1" mission = "m1 m2 m3">
			<first-name>Честър</first-name>
			<last-name>Нимитц</last-name>
			<gender>мъж</gender>
			<position>адмирал на флоата</position>
			<age>57</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s2" mission = "m1">
			<first-name>Франк</first-name>
			<last-name>Флетчър</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>57</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s3" mission = "m1">
			<first-name>Реймънд</first-name>
			<last-name>Шпруанс</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>56</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s4" mission = "m1">
			<first-name>Марк</first-name>
			<last-name>Митчър</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>55</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s5" mission = "m1">
			<first-name>Томас</first-name>
			<last-name>Кинкейд</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>54</age>
			<religion>християнин</religion>
		</soldier>
	</personel>
	<aircrafts>
		<aircraft id = "a4" control = "pilot" role = "fighter">
			<model>F-15 Eagle</model>
			<manufacturer>
				<manufacturer-name>McDonnell Douglas</manufacturer-name>
				<established>28 April 1967</established>
				<staff-count>50000</staff-count>
				<profit>US$ 20.30 billion</profit>
			</manufacturer>
			<cost>28 million USD</cost>
			<range>1967 km</range>
		</aircraft>
	</aircrafts>
	<missions>
		<mission id="m1">
			<code-name>Pearl Harbor</code-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>един ден</duration>
			<description>Нападението над Пърл Харбър е изненадваща въздушна атака на японския Императорски флот срещу американската военноморска база при Пърл Харбър, Хаваи, извършена сутринта на 7 декември 1941 г.
				Без предварително обявяване на война базата е атакувана от 353 японски бойни самолети, бомбардировачи и торпедоносци на две вълни, изстрелвани от шест самолетоносача. Унищожена е голяма част от американския тихоокеански военноморски флот. Поради това през следващите месеци японците има пълно надмощие в Тихия океан. Едновременно с атаката започва японската офанзива срещу британските и холандските колонии в Югоизточна Азия, с което Втората световна война става фактически глобална война. Атаката над Пърл Харбър е битка, при която самолетоносачите и линейните кораби са доминиращият елемент.
				Атаката е повратна точка в развоя на Втората световна война, тъй като става повод за влизането на САЩ, която да този момент е неутрална, във войната. Въпреки, че атаката причинява на САЩ значителни военни загуби, тя се оказва с фатални последствия за Япония. На следващия ден (8 декември) САЩ обявява война на Япония.
			</description>
			<units-lost></units-lost>
		</mission>
		<mission id="m2">
			<code-name>Битка при Мидуей</code-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>три дни</duration>
			<description>
				Битката при атола Мидуей се състои на 4 юни 1942 година и е една от най-значителните морски битки на Втората световна война. Флотът на САЩ побеждава обединения флот на Япония, който атакува атола Мидуей. Битката бележи повратен момент във войната в Тихия океан. Обединеният флот на Япония губи 4 тежки самолетоносача, 250 самолета и най-добрите си пилоти, с което загубва възможностите си да действа извън зоната на прикритие на бреговата авиация.
			</description>
			<units-lost></units-lost>
		</mission>
		<mission id="m3">
			<code-name>Битката при островите Санта Круз</code-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>три дни</duration>
			<description>
				Битката при атола Мидуей се състои на 4 юни 1942 година и е една от най-значителните морски битки на Втората световна война. Флотът на САЩ побеждава обединения флот на Япония, който атакува атола Мидуей. Битката бележи повратен момент във войната в Тихия океан. Обединеният флот на Япония губи 4 тежки самолетоносача, 250 самолета и най-добрите си пилоти, с което загубва възможностите си да действа извън зоната на прикритие на бреговата авиация.
			</description>
			<units-lost></units-lost>
		</mission>
		<mission id="m4">
			<code-name>Битката за Иво Джима</code-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>три дни</duration>
			<description>
				Битката при атола Мидуей се състои на 4 юни 1942 година и е една от най-значителните морски битки на Втората световна война. Флотът на САЩ побеждава обединения флот на Япония, който атакува атола Мидуей. Битката бележи повратен момент във войната в Тихия океан. Обединеният флот на Япония губи 4 тежки самолетоносача, 250 самолета и най-добрите си пилоти, с което загубва възможностите си да действа извън зоната на прикритие на бреговата авиация.
			</description>
			<units-lost></units-lost>
		</mission>
	</missions>
</aircraft-carrier>

=== mihail-jekov/fmiXMLCourse/Valid_XML_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aircraft-carrier SYSTEM "AircraftCarrier.dtd">
<?xml-stylesheet type="text/xsl" href="HTML_Transformation_1.xsl"?>

<aircraft-carrier engine = "nuclear" class = "USS Nimitz" years-of-service = "1975-present">
	<name>Nimitz</name>
	<personel>
		<soldier id = "s1" aircraft = "a4">
			<first-name>Takijiro</first-name>
			<last-name>Ohnishi</last-name>
			<gender>male</gender>
			<position>General</position>
			<age>36</age>
			<religion>Shinto</religion>
		</soldier>
	</personel>
	<aircrafts>
		<aircraft id = "a4" control = "pilot" role = "fighter">
			<model>F-15 Eagle</model>
			<manufacturer>
				<manufacturer-name>McDonnell Douglas</manufacturer-name>
				<established>28 April 1967</established>
				<staff-count>50000</staff-count>
				<profit>US$ 20.30 billion</profit>
			</manufacturer>
			<cost>28 million USD</cost>
			<range>1967 km</range>
		</aircraft>
		<aircraft id = "a5" control = "pilot" role = "bomber">
			<model>F-16 Fighting Falcon</model>
			<manufacturer>
				<manufacturer-name>General Dynamics</manufacturer-name>
				<established>1899</established>
				<staff-count>92200</staff-count>
				<profit>31.513 милярда</profit>
			</manufacturer>
			<cost>14.6 милиона долара</cost>
			<range>1100 километра</range>
		</aircraft>
		<aircraft id = "a6" control = "pilot" role = "bomber">
			<model>F-22 Raptor</model>
			<manufacturer>
				<manufacturer-name>Lockheed Martin</manufacturer-name>
				<established>1995</established>
				<staff-count>116000</staff-count>
				<profit>$2.981 милярда</profit>
			</manufacturer>
			<cost>150 милиона долара</cost>
			<range>2960 км</range>
		</aircraft>
		<aircraft id = "a7" control = "pilot" role = "bomber">
			<model>B-2 Spirit</model>
			<manufacturer>
				<manufacturer-name>Northrop Grumman</manufacturer-name>
				<established>1994</established>
				<staff-count>68100</staff-count>
				<profit>1.952 милярда</profit>
			</manufacturer>
			<cost>737 милиона долара</cost>
			<range>11100 км</range>
		</aircraft>
		<aircraft id = "a8" control = "pilot" role = "bomber">
			<model>EA-18G Growler</model>
			<manufacturer>
				<manufacturer-name>Boeing</manufacturer-name>
				<established>1916</established>
				<staff-count>168421</staff-count>
				<profit>$4.585 милярда</profit>
			</manufacturer>
			<cost>68.2 милиона долара</cost>
			<range>2346 км</range>
		</aircraft>
		<aircraft id = "a9" control = "pilot" role = "bomber">
			<model>F-35 Lightning II</model>
			<manufacturer>
				<manufacturer-name>Lockheed Martin Aeronautics</manufacturer-name>
				<established>1995</established>
				<staff-count>116000</staff-count>
				<profit>$2.981 милярда</profit>
			</manufacturer>
			<cost>142 милиона долара</cost>
			<range>2220 км</range>
		</aircraft>
	</aircrafts>
	<missions>
		
	</missions>
</aircraft-carrier>

=== mihail-jekov/fmiXMLCourse/Valid_XML_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aircraft-carrier SYSTEM "AircraftCarrier.dtd">
<?xml-stylesheet type="text/xsl" href="HTML_Transformation_1.xsl"?>

<aircraft-carrier engine = "nuclear" class = "Charles de Gaulle" years-of-service = "2001-present">
	<name>Charles de Gaulle</name>
	<personel>
		<soldier id = "s1" aircraft = "a4">
			<first-name>Takijiro</first-name>
			<last-name>Ohnishi</last-name>
			<gender>male</gender>
			<position>General</position>
			<age>36</age>
			<religion>Shinto</religion>
		</soldier>
	</personel>
	<aircrafts>
		<aircraft id = "a4" control = "pilot" role = "fighter">
			<model>Rafale</model>
			<manufacturer>
				<manufacturer-name>Dassault Aviation</manufacturer-name>
				<established>1929</established>
				<staff-count>11600</staff-count>
				<profit>487 милиона</profit>
			</manufacturer>
			<cost>74 милиона евро</cost>
			<range>3700 км</range>
		</aircraft>
		<aircraft id = "a5" control = "pilot" role = "bomber">
			<model>Super Étendard</model>
			<manufacturer>
				<manufacturer-name>Dassault Aviation</manufacturer-name>
				<established>1929</established>
				<staff-count>11600</staff-count>
				<profit>487 милиона</profit>
			</manufacturer>
			<cost>12 милиона долара</cost>
			<range>1820 километра</range>
		</aircraft>
		<aircraft id = "a6" control = "pilot" role = "bomber">
			<model>F-22 Raptor</model>
			<manufacturer>
				<manufacturer-name>Lockheed Martin</manufacturer-name>
				<established>1995</established>
				<staff-count>116000</staff-count>
				<profit>$2.981 милярда</profit>
			</manufacturer>
			<cost>150 милиона долара</cost>
			<range>2960 км</range>
		</aircraft>
		<aircraft id = "a7" control = "pilot" role = "bomber">
			<model>E-2 Hawkeye</model>
			<manufacturer>
				<manufacturer-name>Northrop Grumman</manufacturer-name>
				<established>1994</established>
				<staff-count>68100</staff-count>
				<profit>1.952 милярда</profit>
			</manufacturer>
			<cost>176 милиона долара</cost>
			<range>2708 км</range>
		</aircraft>
		<aircraft id = "a8" control = "pilot" role = "bomber">
			<model>SA 365 Dauphin 2</model>
			<manufacturer>
				<manufacturer-name>Airbus Helicopters</manufacturer-name>
				<established>1992</established>
				<staff-count>23000</staff-count>
				<profit>$6.3 милярда</profit>
			</manufacturer>
			<cost>10 милиона долара</cost>
			<range>827 км</range>
		</aircraft>
		<aircraft id = "a9" control = "pilot" role = "bomber">
			<model>EC 725 Super Cougar</model>
			<manufacturer>
				<manufacturer-name>Airbus Helicopters</manufacturer-name>
				<established>1992</established>
				<staff-count>23000</staff-count>
				<profit>$6.3 милярда</profit>
			</manufacturer>
			<cost>24.5 милиона долара</cost>
			<range>857 км</range>
		</aircraft>
	</aircrafts>
	<missions>
		
	</missions>
</aircraft-carrier>
